FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY model_nutrition_stat.h5 /app/model_nutrition_stat.h5
COPY food-data.csv .
COPY labels.json .

EXPOSE 8080

CMD ["python", "app.py"]